export component NavButton {
    in property<string> button-text: "";
    in property<bool> active: false;
    callback clicked;

    Rectangle {
        width: 100%;
        height: 100%;
        background: active ? #3498db : #95a5a6;
        border-radius: 4px;

        Text {
            text: button-text;
            color: #ffffff;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        TouchArea {
            clicked => {
                clicked();
            }
        }
    }
}
