import { Tokens } from "@styles";

export component CommonBtn inherits Rectangle {
    in property<string> text: "";
    in property<bool> primary: false;

    // button could be disable. Callback can only be invoked when enabled is true.
    in-out property<bool> enabled: true;
    // if the button is clicked, button state changes. Useful for toggle button, in flashcard
    in-out property<bool> checked: false;
    // if the button is checkable, it can be checked or unchecked when clicked. Otherwise, it behaves like a normal button without checked state. Useful for mutual exclusive button group, in flashcard stack list.
    in property<bool> checkable: false;
    // if the button is pressed, it is being clicked. Useful for visual feedback when user clicks and holds the button.
    out property<bool> pressed <=> ta.pressed;

    in property<string> accessibilityLabel: "";
    in property<string> accessibilityDescription: "";
    in property<string> accessibilityId: "";

    callback clicked;

    width: 100%;
    height: 40px;
    border-radius: 8px;
    accessible-role: button;
    accessible-label: accessibilityLabel != "" ? accessibilityLabel : text;
    accessible-description: accessibilityDescription;
    accessible-id: accessibilityId;
    accessible-enabled: enabled;
    accessible-checkable: checkable;
    accessible-checked: checked;
    background: !enabled ? Tokens.btn-disabled-bg
        : (checked ? Tokens.nav-background
        : (primary ? Tokens.btn-primary-bg
        : Tokens.btn-default-bg));
    opacity: pressed ? 0.9 : (enabled ? 1.0 : 0.85);

    HorizontalLayout {
        padding: 10px;
        alignment: center;

        Text {
            text: text;
            color: !enabled ? Tokens.btn-disabled-text : Tokens.text-on-dark;
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: Tokens.font-size-input;
        }
    }

    ta:=TouchArea {
        enabled: enabled;
        clicked => {
            if (checkable) {
                checked = !checked;
            }
            if (enabled) {
                clicked();
            }
        }
    }

    accessible-action-default => {
        if (enabled) {
            clicked();
        }
    }
}
